FROM rust:latest as builder

WORKDIR /rlink-rs

ADD ./ ./

#COPY ./docker/config.toml .cargo/

RUN cargo build --bin rlink-example-simple --release

FROM debian:latest

RUN apt update

RUN apt install openssl procps linux-perf -y

COPY  --from=builder /rlink-rs/target/release/rlink-example-simple /usr/local/bin

ENTRYPOINT  ["rlink-example-simple"] 
